#!/bin/bash
set -euo pipefail

octo_release_command=("octo" "create-release" "--progress" "--project=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PROJECT")

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENUMBER:-}" ]] ; then
    octo_release_command+=("--releaseNumber=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENUMBER")
    PLUGIN_INTERNAL_RELEASE_URL=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENUMBER
fi

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PACKAGEVERSION:-}" ]] ; then
    octo_release_command+=("--packageVersion=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PACKAGEVERSION")
    PLUGIN_INTERNAL_RELEASE_URL=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PACKAGEVERSION
fi

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASECHANNEL:-}" ]] ; then
    octo_release_command+=("--channel=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASECHANNEL")
fi

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENOTESARTIFACTNAME:-}" ]] ; then
    buildkite-agent artifact \
        download \
        "$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENOTESARTIFACTNAME" \
        "."
    
    octo_release_command+=("--releaseNotesFile=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENOTESARTIFACTNAME")
fi

function run_octorelease() {
    "${octo_release_command[@]}"
}

# Octopus Release Annotation
cat << EOF | buildkite-agent annotate --context 'buildkite-plugin-octopus-release-' --style 'info'
## Octopus Release [$PLUGIN_INTERNAL_RELEASE_URL]($OCTOPUS_CLI_SERVER/app#/projects/$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PROJECT/deployments/releases/$PLUGIN_INTERNAL_RELEASE_URL)
EOF

echo "--- :hammer: Running octo"
printf "%q " "${octo_release_command[@]}"
echo

run_octorelease
exit 0
