#!/bin/bash
set -euo pipefail

function plugin_read_config() {
  local var="BUILDKITE_PLUGIN_OCTOPUS_RELEASE_${1}"
  local default="${2:-}"
  echo "${!var:-$default}"
}


octo_command=("octo" "create-release" "--progress" "--project=${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PROJECT}")

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PACKAGEVERSION:-}" ]] ; then
    octo_command+=("--packageVersion=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PACKAGEVERSION")
fi

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENUMBER:-}" ]] ; then
    octo_command+=("--releaseNumber=$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENUMBER")
fi

if [[ -n "${BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENOTESARTIFACTNAME:-}" ]] ; then
    buildkite-agent artifact \
        download \
        "$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_RELEASENOTESARTIFACTNAME" \
        "releaseNotes.md"
    
    octo_command+=("--releaseNotesFile=releaseNotes.md")
fi

function run_octorelease() {
    "${octo_command[@]}"
}


echo "$BUILDKITE_PLUGIN_OCTOPUS_RELEASE_PROJECT"
echo "$OCTOPUS_PROJECT_NAME"
echo "--- :hammer: Running octo"
printf "%q " "${octo_command[@]}"
echo

run_octorelease
exit 0